######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 25 18:48:16 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp MainWindow.cpp ControlWindow.cpp TemperatureWindow.cpp
HEADERS += MainWindow.h ControlWindow.h TemperatureWindow.h
